package com.experian.aperture.streaming.client.response;

import com.google.gson.annotations.SerializedName;

/**
 * Error model containing the error details.
 */
public final class ResponseError {
    /**
     * A link to documentation that provides more details about the error you’ve encountered.
     *
     * @return type
     **/
    @SerializedName("type")
    private String type;

    /**
     * The title of the error.
     * Examples: Bad Request.
     *
     * @return title
     **/
    @SerializedName("title")
    private String title;

    /**
     * The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
     * @return status
     **/
    @SerializedName("status")
    private int status;

    /**
     * A description of the error.
     * Examples: The request body was malformed.
     *
     * @return detail
     **/
    @SerializedName("detail")
    private String detail;

    /**
     * The endpoint that returned the error.
     * @return instance
     **/
    @SerializedName("instance")
    private String instance;

    public String getType() {
        return this.type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public String getTitle() { return this.title; }

    public void setTitle(final String title) { this.title = title; }

    public int getStatus() { return this.status; }

    public void setStatus(final int status) { this.status = status; }

    public String getDetail() { return this.detail; }

    public void setDetail(final String detail) { this.detail = detail; }

    public String getInstance() { return this.instance; }

    public void setInstance(final String instance) { this.instance = instance; }
}